services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgressuser
      POSTGRES_PASSWORD: postgresspassword
      POSTGRES_DB: postgressuser
    restart: always
    networks:
      - lesson
networks:
  lesson: